name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Use node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - run: yarn install --immutable

      - run: yarn test

      - run: yarn lint
